default_resources:
  gres: ""
  mem_mb: 9216
  mem_per_cpu: 9216
  partition: "core"
  threads: 1
  time: "24:00:00"

fastp_pe:
  mem_mb: 147456
  threads: 8

glnexus:
  threads: 20

pbrun_fq2bam:
  gres: "--gres=gpu:4"
  mem_mb: 163840
  mem_per_cpu: 4096
  partition: "GPU"
  threads: 40
  time: "20:00:00"

pbrun_deepvariant:
  gres: "--gres=gpu:2"
  mem_mb: 81920
  mem_per_cpu: 4096
  partition: "GPU"
  threads: 20
  time: "20:00:00"

pbrun_glnexus:
  gres: "--gres=gpu:2"
  mem_mb: 81920
  mem_per_cpu: 4096
  partition: "GPU"
  threads: 20
  time: "20:00:00"

peddy:
  threads: 8

mosdepth:
  mem_mb: 36864
  threads: 4

mosdepth_bed:
  mem_mb: 36864
  threads: 4

spring:
  mem_mb: 368640
  threads: 8
